<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * @property int $id
 * @property string $name
 * @property string $description
 * @property string $img_link
 * @property string $video_link
 * @property string $mod_link
 * @property string $user_id
 * @property string $game_id
 * @property MapLike[] $likes
 * @property MapComment[] $comments
 * @property Game $game
 * @property User $user
 */
class Map extends ActiveRecord
{

    public function beforeSave($insert)
    {

        if (str_contains($this->video_link, 'youtube')) {
            $this->video_link = explode('?v=', explode('&', $this->video_link)[0])[1];
        } else {
            $this->video_link = null;
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function attributeLabels(): array
    {
        return [
            'name' => 'Название',
            'description' => 'Описание',
            'img_link' => 'Ссылка на фото',
            'video_link' => 'Ссылка на видео с YouTube',
            'mod_link' => 'Ссылка на мод',
            'game_id' => 'Игра',
        ];
    }

    public static function tableName(): string
    {
        return '{{maps}}';
    }

    public function getLikes()
    {
        return $this->hasMany(MapLike::class, ['map_id' => 'id']);
    }

    public function getComments()
    {
        return $this->hasMany(MapComment::class, ['map_id' => 'id']);
    }

    public function getGame()
    {
        return $this->hasOne(Game::class, ['id' => 'game_id']);
    }
    
    public function getUser()
    {
        return $this->hasOne(User::class,['id'=>'user_id']);
    }
}
